
[admin:TA_DellEMC_VMAX]
match = /
members = TA_DellEMC_VMAX_settings, TA_DellEMC_VMAX_inputs

[admin_external:TA_DellEMC_VMAX_settings]
handlertype = python
python.version = python3
handlerfile = TA_DellEMC_VMAX_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_DellEMC_VMAX_inputs]
handlertype = python
python.version = python3
handlerfile = TA_DellEMC_VMAX_rh_inputs.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
